version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: aiden_redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
